name = "file-share"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-10-02"
assets = { directory = "./public" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "fileShare"
id = "925af48eb93241be84ad3ad32b2a9cb3"
