name = "file-share"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2026-02-20"

[assets]
directory = "./public"
binding = "ASSETS"

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "fileShare"
id = "ca4aa4fb3fbf45179c7724dbb88283d3"
